version: "3.8"
services:
   frontend:
     build:
       context: .
       dockerfile: Dockerfile.dev
     volumes:
       - ./:/react-docker:delegated
       - /node_modules
     ports:
       - 3001:3001
     environment:
       - CHOKIDAR_USEPOLLING=true